name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:

jobs:
  rustfmt:
    name: Formatting check
    runs-on: ubuntu-latest
    container: kisiodigital/rust-ci:latest-proj8.1.0
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    steps:
    - uses: actions/checkout@v3
    - name: Run cargo fmt
      run: |
        cargo fmt --all -- --check
  clippy:
    name: Analyzing code with Clippy
    runs-on: ubuntu-latest
    container: kisiodigital/rust-ci:latest-proj8.1.0
    steps:
    - uses: actions/checkout@master
    - name: Run cargo clippy
      run: |
        cargo clippy --workspace --all-features -- -D warnings
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: kisiodigital/rust-ci:latest-proj8.1.0
    steps:
    - uses: actions/checkout@master
    - name: Run tests without features
      run: |
        cargo test --workspace --verbose
    - name: Run tests with 'log' feature
      run: |
        cargo test --workspace --verbose --features log
    - name: Run tests with 'tracing' feature
      run: |
        cargo test --workspace --verbose --features tracing
    - name: Run tests with all features
      run: |
        cargo test --workspace --verbose --all-features
