name: Continuous Integration
on: [push, pull_request]

jobs:
  rustfmt:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: rustfmt
    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: Analyzing code with Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy
    - name: Run cargo clippy
      run: cargo clippy --workspace --all-features --message-format=json -- --warn clippy::pedantic > clippy.json
    - name: Run sonarqube
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: > 
          -Dsonar.projectKey=CanalTP_skip_error
          -Dsonar.projectName=skip_error
          -Dsonar.sources=src/
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.rust.clippy.reportPaths=clippy.json
          -Dsonar.organization=canaltp
          -Dsonar.verbose=true
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-features -- -D warnings

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, beta]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
    steps:
    - uses: actions/checkout@master
    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
    - name: Run tests without features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --verbose
    - name: Run tests with 'log' feature
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --verbose --features log
    - name: Run tests with 'tracing' feature
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --verbose --features tracing
    - name: Run tests with all features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --verbose --all-features
